[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "dermvision"
authors = [{name = "Mo Oyedeji", email = "mojeed.oyedeji@gmail.com"}]
dynamic = ["version", "description"]
